beepy-kbd 2.12-1:   * Removed hard dependency on sharp-drm and beepy-fw   * Removed a bunch of postrm and preinst (i.e. dphys-swapfile) hooks that might be suboptimal to force   * Temporarily commenting out the firmware version checks (until we package our firmware)

diff --git a/beepy-kbd-2.12/debian/preinst b/beepy-kbd-2.12/debian/preinst
--- a/beepy-kbd-2.12/debian/preinst
+++ b/beepy-kbd-2.12/debian/preinst
@@ -16,14 +16,14 @@ if modprobe -n bbqX0kbd 2>/dev/null; then
 fi
 
 # Check for swap size on arm64
-if [ "$(uname -m )" == "aarch64" ]; then
-	. /etc/dphys-swapfile
-	if (( CONF_SWAPSIZE < 512 )); then
-		echo "error: CONF_SWAPSIZE detected as $CONF_SWAPSIZE"
-		echo "Please edit /etc/dphys-swapfile, increase to at least 512, and reboot"
-		exit 1
-	fi
-fi
+#if [ "$(uname -m )" == "aarch64" ]; then
+#	. /etc/dphys-swapfile
+#	if (( CONF_SWAPSIZE < 512 )); then
+#		echo "error: CONF_SWAPSIZE detected as $CONF_SWAPSIZE"
+#		echo "Please edit /etc/dphys-swapfile, increase to at least 512, and reboot"
+#		exit 1
+#	fi
+#fi
 
 # Get firmware version
 
@@ -54,20 +54,24 @@ else
 fi
 
 # Check firmware version
-if [ $major -ne $REQ_MAJOR ] || [ $minor -lt $REQ_MINOR ]; then
-	echo "error: driver requires firmware version $REQ_MAJOR.$REQ_MINOR" \
-		"(firmware has version $major.$minor)"
-	echo "update the beepy-fw package and run"
-	echo "    /sbin/update-beepy-fw"
-	echo -e "or manually install the firmware release from\n    $RELEASE_PAGE"
-	exit 1
-fi
-if [ $minor -lt $SUG_MINOR ]; then
-	echo "warning: installed firmware version $major.$minor is compatible," \
-		"but out of date (driver may use features from version $REQ_MAJOR.$SUG_MINOR)"
-	echo "consider updating the beepy-fw package to $REQ_MAJOR.$SUG_MINOR and run"
-	echo "    /sbin/update-beepy-fw"
-	echo -e "or manually install the firmware release from\n    $RELEASE_PAGE"
-fi
+# TODO it maybe should not fail if the fw MAJOR is higher than driver MAJOR
+# INCOMPLETE
+#if [ $major -lt $REQ_MAJOR ] || [ $minor -lt $REQ_MINOR ]; then
+#	echo "error: driver requires firmware version $REQ_MAJOR.$REQ_MINOR" \
+#		"(firmware has version $major.$minor)"
+#	echo "update the beepy-fw package and run"
+#	echo "    /sbin/update-beepy-fw"
+#	echo -e "or manually install the firmware release from\n    $RELEASE_PAGE"
+#	exit 1
+#fi
+
+# Check firmware version
+#if [ $minor -lt $SUG_MINOR ]; then
+#	echo "warning: installed firmware version $major.$minor is compatible," \
+#		"but out of date (driver may use features from version $REQ_MAJOR.$SUG_MINOR)"
+#	echo "consider updating the beepy-fw package to $REQ_MAJOR.$SUG_MINOR and run"
+#	echo "    /sbin/update-beepy-fw"
+#	echo -e "or manually install the firmware release from\n    $RELEASE_PAGE"
+#fi
 
 echo "Firmware version $major.$minor passes module requirement"
